services:
  # 1. Konfigurasi Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: kumpulbareng_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  # 2. Konfigurasi Backend Server
  server:
    # Build dari Dockerfile di dalam folder ./server
    build: ./server
    ports:
      - "5000:5000"
    environment:
      # Server akan terhubung ke database melalui nama service 'db'
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/kumpulbareng_db"
      CLIENT_URL: "http://localhost:3000"
      JWT_SECRET: "${JWT_SECRET:-CHANGE_ME_FOR_LOCAL_DEV}"
    # Tunggu hingga service 'db' siap sebelum memulai 'server'
    depends_on:
      - db

  # 3. Konfigurasi Frontend Client
  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:5000"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - server

volumes:
  db-data: